FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Movie.API.csproj", "./"]
RUN dotnet restore "Movie.API.csproj"

COPY . .
RUN dotnet publish "Movie.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

EXPOSE 8080

COPY --from=build /app/publish .
COPY wwwroot/ /app/wwwroot/

ENTRYPOINT ["dotnet", "Movie.API.dll"]